# Generated by Django 5.0.7 on 2025-08-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butchery', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descritpion',
            new_name='description',
        ),
    ]
