# Generated by Django 5.0.7 on 2025-08-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butchery', '0007_stocktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOBILE', 'Mobile Money')], default='CASH', max_length=20),
        ),
    ]
